### ISSUE TITLE
Roads not showing up 

### ISSUE THREAD

**Issue by see24** [LandSciTech/roads#2]
This works for me with the data Josie sent
```
devtools::load_all(".")
outObj <- readRDS("../../../Downloads/roadInputs.RDS")
roadsCH <- raster::raster("../../../Downloads/churchillRoadRaster.tif")
raster::crs(roadsCH) <- raster::crs(outObj$roads)
raster::extent(roadsCH) <- raster::extent(outObj$roads)
raster::origin(roadsCH) <- raster::origin(outObj$roads)
raster::res(roadsCH) <- raster::res(outObj$roads)
outObj$roads <- roadsCH
sim_mst = projectRoadsNew(outObj$landings,
                      outObj$cost,
                      outObj$roads,
                      roadMethod="mst",
                      roadsOut = "raster")
```
the roadsOut part shouldn't change anything because it is the default

I get results but they don't look very good with some points not getting connected to the road network

I have noticed though that the cost is 0 in some areas that don't have roads yet which is probably messing things up. 
`plot(outObj$roads)`
![image](https://user-images.githubusercontent.com/39161074/108272482-48e8e400-7140-11eb-8d5e-a8d73ccd8c35.png)
`plot(outObj$cost == 0)`
![image](https://user-images.githubusercontent.com/39161074/108272596-76359200-7140-11eb-8af8-f93e8d047f78.png)

**Comment by josie-hughes** [comment]
This is ok after all. A visualization problem due to NAs in the initialRoads layer.
