### ISSUE TITLE
add pfocal to Suggests when on CRAN again

### ISSUE THREAD

**Issue by see24** [LandSciTech/roads#22]
pfocal should be in Suggests but that doesn't work when it is not on CRAN so it should be added later. The current plan allows pkgdown to work but fails to pass the check.

**Comment by see24** [comment]
Used Remotes in description to make pfocal work for pkgdown but that won't work for CRAN so will need to change.

https://remotes.r-lib.org/articles/dependencies.html

**Comment by achubaty** [comment]
Assuming that package is already used condiitonally, you can supply an R-universe repo to `Additional_repositories` in your DESCRIPTION, and make a version of the package available through an r-unverse repo on GitHub. (This is fairly easy to setup, and will auto build whichever packages you ask it to for the various platforms.)

We do this for [`SpaDES.tools`](https://github.com/PredictiveEcology/SpaDES.tools/blob/master/DESCRIPTION#75) which uses `NLMR` (formerly on CRAN but not yet restored). See https://github.com/PredictiveEcology/universe.

**Comment by see24** [comment]
Thanks Alex! I did try using `Additional_repositories` with the drat repo that I set up which has `pfocal`. But I did not have success getting that to work for the `pkgdown` site so ended up with the Remotes solution. 

I will check out your `SpaDES.tools` example though and see if that will show me what I was getting wrong

**Comment by see24** [comment]
No longer need pfocal
