### ISSUE TITLE
error with raster-dev

### ISSUE THREAD

**Issue by rhijmans** [LandSciTech/roads#28]
When checking "roads" with the dev version of "raster" (https://github.com/rspatial/raster) I now get
  
```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-errors-messages.R:8:3'): different CRS is error ──────────────
  `projectRoads(CLUSexample$landings, cost, rds)` did not throw an error.
 ```

This is because of changes in "raster" related to the changes in the "sp family" packages. sp::identicalCRS does not work well with Raster* objects any more. 

You now need to use CRS(Raster*) or you could use terra::same.crs(x, y). (The best approach might be to drop "raster" and only use "terra").

Can you please fix this so that your package won't break when I submit "raster" to CRAN?

**Comment by see24** [comment]
@rhijmans yes, I have some time tomorrow when I can work on this, hopefully won't be too difficult. 
We have transitioned the package to terra and sf but are still trying to support raster and sp inputs, not sure if that is the issue or if I missed something in the transition. Thanks for mentioning terra::same.crs I don't think I had seen it yet!

**Comment by rhijmans** [comment]
I do not know what you can or cannot do in `.onLoad`.  But I suppose that in onLoad you would assign the data to a variable in the workspace and that is probably not a good idea?

I would suggest a function like this

```
CLUSexdata <- function() {
       data(CLUSexample)
       CLUSexample[[1]] <- terra::rast(CLUSexample[[1]] )
       CLUSexample[[3]] <- terra::rast(CLUSexample[[3]] )
       CLUSexample
 }
```
(where the original rasters become wrapped SpatRasters, but it also works with the current data; or you could use TIFF files.) 

In the examples you can then do:

```
exdata <- CLUSexdata() 
```

And I think that is very transparent. 

Now since the example data are really small, you could also just do:

```
CLUSexdata <- function() {
	list(
		cost=rast(ncols=5, nrows=5, xmin=0, xmax=5, ymin=0, ymax=5, crs='', vals=c(0.000000, 0.000000, 0.000000, 0.000000, 0, 18.069404, 18.948830, 13.555158, 12.953167, 2.173939, 4.913517, 4.354578, 14.053434, 8.297971, 15.626987, 10.456286, 14.634752, 19.846216, 8.220668, 15.771459, 18.759399, 5.030708, 13.381802, 3.385547, 6.077193)),
		
		landings=vect(matrix(c(0.5, 2.5, 1.5, 4.5, 2.5, 2.5, 0.5, 0.5), ncol=2)),
		
		roads=rast(ncols=5, nrows=5, xmin=0, xmax=5, ymin=0, ymax=5, crs='', vals=c(TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE))
	)
}
```

**Comment by see24** [comment]
@rhijmans Thanks for your help on this. One more follow up for you:

I now have the packed SpatRasters stored in CLUSexample and I added a function prepExData that does the unwrapping. 
This works fine if terra is loaded before I try to access the CLUSexample data but fails with a strange error if I do not load terra:

```r
library(roads)
# The legacy packages maptools, rgdal, and rgeos, underpinning this package
# will retire shortly. Please refer to R-spatial evolution reports on
# https://r-spatial.org/r/2023/05/15/evolution4.html for details.
# This package is now running under evolution status 0 
CLUSexample
# $cost
# Loading required package: terra
# Error: package or namespace load failed for ‘terra’ in .doLoadActions(where, attach):
#  error in load action .__A__.1 for package terra: loadModule(module = "spat", what = TRUE, env = ns, loadNow = TRUE):
# Unable to load module "spat": attempt to apply non-function
# Error in .requirePackage(package) : 
#  unable to find required package ‘terra’
# In addition: Warning message:
# package ‘terra’ was built under R version 4.2.3 
```

Is there something I need to do in the package setup to make this work or is it unexpected for terra to do this?

**Comment by rhijmans** [comment]
I tried to install the  28-error-with-raster-dev fork but that failed and I do not see prepExData. 
I wonder if you can use .onAttach (rather than .onLoad of that is what you are using).

**Comment by see24** [comment]
Sorry @rhijmans! I hadn't pushed. I just did so you should see what I am talking about now. I also changed my demoScen example data set which has the same issue.

**Comment by see24** [comment]
I believe I have fixed this issue and another one that only showed up in R CMD CHECK for sf objects. In both cases I imported a function from the package and that I guess means it is loaded when roads is. This fixed the issues.

**Comment by see24** [comment]
roads 1.1.1 is now on CRAN. I have removed all dependencies on raster and sp although these objects are still allowed as inputs.
