### ISSUE TITLE
Making getLandings work for all the different scenarios

### ISSUE THREAD

**Issue by see24** [LandSciTech/roads#6]
Old version of `getLandingsFromTarget`
```
rast <- demoScen[[1]]$landings.poly %>% raster::rasterize(demoScen[[1]]$cost.rast)
  # make sure that a single celled havest block will work with clumps
  rast[10,10] <- 6
  outOld <- getLandingsFromTarget(rast > 0, numLandings = 614*0.1)
```
![image](https://user-images.githubusercontent.com/39161074/110689754-0fd8e800-81b1-11eb-9f91-16f431751b90.png)

New version
```
  rast <- demoScen[[1]]$landings.poly %>% raster::rasterize(demoScen[[1]]$cost.rast)
  # make sure that a single celled havest block will work with clumps
  rast[10,10] <- 6
  
  out <- getLandingsFromHarvest(rast, 0.25)
```
![image](https://user-images.githubusercontent.com/39161074/110698760-0f921a00-81bc-11eb-8b63-2be48640e9ff.png)

The new version is quite different but I think is an improvement since it uses a regular sampling grid to get points with in the polygon rather than random sampling so the resulting points are spread out in the polygon rather than some of them ending up side by side which isn't very realistic. It is also easier to set numLandings since it is the density of landings

It took 3.5 mins to get 90777 points in 10338 polygons takes longer the higher the density of points

This isn't so much an issue as a request for comment. If @josie-hughes you think it is ok I will rename it to getLandingsFromTarget and remove the old version. Old code will have to be changed to reflect the new meaning of numLandings which is 1/[distance between points on the grid] (we could make it simply the distance between points in the grid but I was thinking of it as density so smaller equals further apart)

**Comment by josie-hughes** [comment]
Thanks Sarah. 3.5 mins seems longish - I am a bit concerned about substantially adding to the compute time for raster projection results where there is already a grid and it is quick and easy to select points on that grid. 
Let me mess around with applying to my Churchill example and get back to you about this next week.

**Comment by see24** [comment]
Yes it is a bit long but it very dependent on the number of points. For example if I change the point density from 0.005 pts/m2 to 0.001 pts/m2 it takes 10 seconds instead of 3.5 minutes, mostly because fewer polygons have to be intersected with the point grid because if a polygon only needs on point I just use the centroid. 

I was mostly looking to make what already works for rasters work for polygons too but I think you are right that it would be better to get the points directly from the raster if the input is raster since that is faster. Do you think the regular sampling is an improvement though? I have changed the raster version of the function to use that and the result looks like this and shouldn't take any longer:

![image](https://user-images.githubusercontent.com/39161074/111331221-10f19580-8647-11eb-9af4-72e75c8f022a.png)

I have kept the centroid as well as the grid of points to ensure that all clumps get at least one landing. This way number of landings can be given as a density of points which determines the spacing of the grid of points

**Comment by josie-hughes** [comment]
Thanks. Grid sampling is likely better, but would be interesting to formally look at performance of random vs grid in David's example area.

**Comment by see24** [comment]
Okay, I will make a samplingType argument so we can use either option.
